language: python

python:
  - "3.5"

sudo: false

env:
    - TOX_ENV=py34-django18-drf34
    - TOX_ENV=py34-django18-drf35
    - TOX_ENV=py34-django19-drf34
    - TOX_ENV=py34-django19-drf35
    - TOX_ENV=py34-django110-drf34
    - TOX_ENV=py34-django110-drf35
    - TOX_ENV=py35-django18-drf34
    - TOX_ENV=py35-django18-drf35
    - TOX_ENV=py35-django19-drf34
    - TOX_ENV=py35-django19-drf35
    - TOX_ENV=py35-django110-drf34
    - TOX_ENV=py35-django110-drf35

matrix:
  fast_finish: true

install:
  - pip install tox virtualenv

script:
    - tox -e $TOX_ENV
